# Generated by Django 4.2.4 on 2023-12-01 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_portfolio", "0002_ticker_historicaldata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaldata",
            name="ticker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="user_portfolio.mappedtickers",
            ),
        ),
        migrations.DeleteModel(
            name="Ticker",
        ),
    ]
