# Generated by Django 4.2.1 on 2023-10-29 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_portfolio", "0002_stocksmodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stocksmodel",
            old_name="close_price",
            new_name="close",
        ),
        migrations.RenameField(
            model_name="stocksmodel",
            old_name="high_price",
            new_name="high",
        ),
        migrations.RenameField(
            model_name="stocksmodel",
            old_name="low_price",
            new_name="low",
        ),
        migrations.RenameField(
            model_name="stocksmodel",
            old_name="open_price",
            new_name="open",
        ),
    ]
