# Generated by Django 4.2.4 on 2023-12-01 10:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_portfolio", "0003_alter_historicaldata_ticker_delete_ticker"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalData",
        ),
    ]
