# Generated by Django 3.2.18 on 2023-11-10 11:35

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_portfolio', '0006_updatetimestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='prices',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='prices',
            name='ticker',
        ),
        migrations.DeleteModel(
            name='UpdateTimestamp',
        ),
        migrations.DeleteModel(
            name='Prices',
        ),
        migrations.DeleteModel(
            name='Ticker',
        ),
    ]
