# Generated by Django 3.2.18 on 2023-11-10 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_portfolio', '0007_auto_20231110_1235'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserStockData',
            new_name='UerStrategyModel',
        ),
    ]
