# Generated by Django 3.2.18 on 2023-11-10 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_portfolio', '0008_rename_userstockdata_uerstrategymodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UerStrategyModel',
            new_name='UserStrategyModel',
        ),
    ]
