# Generated by Django 3.2.18 on 2023-11-10 16:11

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portfolio', '0009_rename_uerstrategymodel_userstrategymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstrategymodel',
            name='data',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
