# Generated by Django 3.2.18 on 2023-11-11 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_portfolio', '0010_alter_userstrategymodel_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketAnalysisPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('window', models.IntegerField(default=8)),
                ('nlargest_window', models.IntegerField(default=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
