# Generated by Django 3.2.18 on 2023-11-11 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portfolio', '0011_marketanalysispreferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketanalysispreferences',
            name='start_date',
            field=models.DateField(default=datetime.date(2015, 1, 1)),
        ),
    ]
