# Generated by Django 3.2.18 on 2023-11-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portfolio', '0012_alter_marketanalysispreferences_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstrategymodel',
            name='current_tickers',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='userstrategymodel',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
