# Generated by Django 3.2.18 on 2023-11-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portfolio', '0015_userstrategymodel_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstrategymodel',
            name='balance',
            field=models.IntegerField(default=1000),
        ),
    ]
