# Generated by Django 3.2.18 on 2023-11-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portfolio', '0016_alter_userstrategymodel_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstrategymodel',
            name='balance',
        ),
        migrations.AddField(
            model_name='marketanalysispreferences',
            name='balance',
            field=models.IntegerField(default=1000),
        ),
    ]
