# Generated by Django 3.2.18 on 2023-11-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portfolio', '0020_mappedtickers'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='watchslit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
