# Generated by Django 3.2.18 on 2023-11-21 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_portfolio', '0022_rename_watchslit_portfolio_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='watchlist',
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickers', models.ManyToManyField(related_name='watchlists', to='user_portfolio.MappedTickers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
