# Generated by Django 3.2.18 on 2023-11-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portfolio', '0023_auto_20231121_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='initial_portfolio_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
